<?php
function betaString2Unicode($str) {

}

function uniString2Betacode($str) {

}

// TODO: String -> character functions
// TODO: Finish combination unicode -> betacode conversions (esp. non-grave accents)
// TODO: Add underscore -> long mark (so we can convert betacode from LSJ)

function beta2unicode($betaChunk) {
    if (preg_match('/S\W/', $betaChunk) === 1) {
        return "\u{03C2}";
    } else {
        switch ($betaChunk) {
            case "*A":
                return "\u{0391}";
            case "*B":
                return "\u{0392}";
            case "*G":
                return "\u{0393}";
            case "*D":
                return "\u{0394}";
            case "*E":
                return "\u{0395}";
            case "*Z":
                return "\u{0396}";
            case "*H":
                return "\u{0397}";
            case "*Q":
                return "\u{0398}";
            case "*I":
                return "\u{0399}";
            case "*K":
                return "\u{039A}";
            case "*L":
                return "\u{039B}";
            case "*M":
                return "\u{039C}";
            case "*N":
                return "\u{039D}";
            case "*C":
                return "\u{039E}";
            case "*O":
                return "\u{039F}";
            case "*P":
                return "\u{03A0}";
            case "*R":
                return "\u{03A1}";
            case "*S":
                return "\u{03A3}";
            case "*T":
                return "\u{03A4}";
            case "*U":
                return "\u{03A5}";
            case "*F":
                return "\u{03A6}";
            case "*X":
                return "\u{03A7}";
            case "*Y":
                return "\u{03A8}";
            case "*W":
                return "\u{03A9}";
            case "A":
                return "\u{03B1}";
            case "B":
                return "\u{03B2}";
            case "G":
                return "\u{03B3}";
            case "D":
                return "\u{03B4}";
            case "E":
                return "\u{03B5}";
            case "Z":
                return "\u{03B6}";
            case "H":
                return "\u{03B7}";
            case "Q":
                return "\u{03B8}";
            case "I":
                return "\u{03B9}";
            case "K":
                return "\u{03BA}";
            case "L":
                return "\u{03BB}";
            case "M":
                return "\u{03BC}";
            case "N":
                return "\u{03BD}";
            case "C":
                return "\u{03BE}";
            case "O":
                return "\u{03BF}";
            case "P":
                return "\u{03C0}";
            case "R":
                return "\u{03C1}";
            case "J":
                return "\u{03C2}";
            case "S":
                return "\u{03C3}";
            case "T":
                return "\u{03C4}";
            case "U":
                return "\u{03C5}";
            case "F":
                return "\u{03C6}";
            case "X":
                return "\u{03C7}";
            case "Y":
                return "\u{03C8}";
            case "W":
                return "\u{03C9}";
            case "I+":
                return "\u{03CA}";
            case "U+":
                return "\u{03CB}";
            case "A)":
                return "\u{1F00}";
            case "A(":
                return "\u{1F01}";
            case "A)\\":
                return "\u{1F02}";
            case "A(\\":
                return "\u{1F03}";
            case "A)/":
                return "\u{1F04}";
            case "A(/":
                return "\u{1F05}";
            case "E)":
                return "\u{1F10}";
            case "E(":
                return "\u{1F11}";
            case "E)\\":
                return "\u{1F12}";
            case "E(\\":
                return "\u{1F13}";
            case "E)/":
                return "\u{1F14}";
            case "E(/":
                return "\u{1F15}";
            case "H)":
                return "\u{1F20}";
            case "H(":
                return "\u{1F21}";
            case "H)\\":
                return "\u{1F22}";
            case "H(\\":
                return "\u{1F23}";
            case "H)/":
                return "\u{1F24}";
            case "H(/":
                return "\u{1F25}";
            case "I)":
                return "\u{1F30}";
            case "I(":
                return "\u{1F31}";
            case "I)\\":
                return "\u{1F32}";
            case "I(\\":
                return "\u{1F33}";
            case "I)/":
                return "\u{1F34}";
            case "I(/":
                return "\u{1F35}";
            case "O)":
                return "\u{1F40}";
            case "O(":
                return "\u{1F41}";
            case "O)\\":
                return "\u{1F42}";
            case "O(\\":
                return "\u{1F43}";
            case "O)/":
                return "\u{1F44}";
            case "O(/":
                return "\u{1F45}";
            case "U)":
                return "\u{1F50}";
            case "U(":
                return "\u{1F51}";
            case "U)\\":
                return "\u{1F52}";
            case "U(\\":
                return "\u{1F53}";
            case "U)/":
                return "\u{1F54}";
            case "U(/":
                return "\u{1F55}";
            case "W)":
                return "\u{1F60}";
            case "W(":
                return "\u{1F61}";
            case "W)\\":
                return "\u{1F62}";
            case "W(\\":
                return "\u{1F63}";
            case "W)/":
                return "\u{1F64}";
            case "W(/":
                return "\u{1F65}";
            case "A)=":
                return "\u{1F06}";
            case "A(=":
                return "\u{1F07}";
            case "H)=":
                return "\u{1F26}";
            case "H(=":
                return "\u{1F27}";
            case "I)=":
                return "\u{1F36}";
            case "I(=":
                return "\u{1F37}";
            case "U)=":
                return "\u{1F56}";
            case "U(=":
                return "\u{1F57}";
            case "W)=":
                return "\u{1F66}";
            case "W(=":
                return "\u{1F67}";
            case "*A)":
            case "*)A":
                return "\u{1F08}";
            case "*A(":
            case "*(A":
                return "\u{1F09}";
            case "*(\A":
            case "*A(\\":
                return "\u{1F0B}";
            case "*A)/":
            case "*)/A":
                return "\u{1F0C}";
            case "*A(/":
            case "*(/A":
            case "*A(=":
                return "\u{1F0F}";
            case "*E)":
            case "*)E":
                return "\u{1F18}";
            case "*E(":
            case "*(E":
                return "\u{1F19}";
            case "*(\E":
            case "*E(\\":
                return "\u{1F1B}";
            case "*E)/":
            case "*)/E":
                return "\u{1F1C}";
            case "*E(/":
            case "*(/E":
                return "\u{1F1D}";
            case "*H)":
            case "*)H":
                return "\u{1F28}";
            case "*H(":
            case "*(H":
                return "\u{1F29}";
            case "*H)\\":
            case ")\\*H":
            case "*)\\H":
                return "\u{1F2A}";
            case "*H)/":
            case "*)/H":
                return "\u{1F2C}";
            case "*)=H":
            case "*H)=":
                return "\u{1F2E}";
            case "(/*H":
            case "*(/H":
                return "\u{1F2F}";
            case "*I)":
            case "*)I":
                return "\u{1F38}";
            case "*I(":
            case "*(I":
                return "\u{1F39}";
            case "*I)/":
            case "*)/I":
                return "\u{1F3C}";
            case "*I(/":
            case "*(/I":
                return "\u{1F3F}";
            case "*O)":
            case "*)O":
                return "\u{1F48}";
            case "*O(":
            case "*(O":
                return "\u{1F49}";
            case "*(\O":
            case "*O(\\":
                return "\u{1F4B}";
            case "*O)/":
            case "*)/O":
                return "\u{1F4C}";
            case "*O(/":
            case "*(/O":
                return "\u{1F4D}";
            case "*U(":
            case "*(U":
                return "\u{1F59}";
            case "*(/U":
                return "\u{1F5D}";
            case "*(=U":
                return "\u{1F5F}";
            case "*W)":
                return "\u{1F68}";
            case "*W(":
            case "*(W":
                return "\u{1F69}";
            case "*W)/":
            case "*)/W":
                return "\u{1F6C}";
            case "*W(/":
            case "*(/W":
            case "*W(=":
            case "*(=W":
                return "\u{1F6F}";
            case "*A)=":
            case "*)=A":
                return "\u{1F0E}";
            case "*W)=":
            case "*)=W":
                return "\u{1F6E}";
            case "A\\":
                return "\u{1F70}";
            case "A/":
                return "\u{1F71}";
            case "E\\":
                return "\u{1F72}";
            case "E/":
                return "\u{1F73}";
            case "H\\":
                return "\u{1F74}";
            case "H/":
                return "\u{1F75}";
            case "I\\":
                return "\u{1F76}";
            case "I/":
                return "\u{1F77}";
            case "O\\":
                return "\u{1F78}";
            case "O/":
                return "\u{1F79}";
            case "U\\":
                return "\u{1F7A}";
            case "U/":
                return "\u{1F7B}";
            case "W\\":
                return "\u{1F7C}";
            case "W/":
                return "\u{1F7D}";
            case "A)/|":
                return "\u{1F84}";
            case "A(/|":
                return "\u{1F85}";
            case "H)|":
                return "\u{1F90}";
            case "H(|":
                return "\u{1F91}";
            case "H)/|":
                return "\u{1F94}";
            case "H)=|":
                return "\u{1F96}";
            case "H(=|":
                return "\u{1F97}";
            case "W)|":
                return "\u{1FA0}";
            case "W(=|":
                return "\u{1FA7}";
            case "A=":
                return "\u{1FB6}";
            case "H=":
                return "\u{1FC6}";
            case "I=":
                return "\u{1FD6}";
            case "U=":
                return "\u{1FE6}";
            case "W=":
                return "\u{1FF6}";
            case "I\\+":
                return "\u{1FD2}";
            case "I/+":
            case "I+/":
                return "\u{1FD3}";
            case "U\\+":
                return "\u{1FE2}";
            case "U/+":
                return "\u{1FE3}";
            case "A|":
                return "\u{1FB3}";
            case "A/|":
                return "\u{1FB4}";
            case "H|":
                return "\u{1FC3}";
            case "H/|":
                return "\u{1FC4}";
            case "W|":
                return "\u{1FF3}";
            case "W|/":
            case "W/|":
                return "\u{1FF4}";
            case "A=|":
                return "\u{1FB7}";
            case "H=|":
                return "\u{1FC7}";
            case "W=|":
                return "\u{1FF7}";
            case "R(":
                return "\u{1FE4}";
            case "*R(":
            case "*(R":
                return "\u{1FEC}";
            case "?":
                return "\u{037E}";
            case ";":
                return "\u{0387}";
            case "_":
                return "\u{0304}";
            default:
                return $betaChunk;
        }
    }
}

function uni2betacode($unicodeChar) {
    switch ($unicodeChar) {
        case "\u{0391}":
            return "*A";
        case "\u{0392}":
            return "*B";
        case "\u{0393}":
            return "*G";
        case "\u{0394}":
            return "*D";
        case "\u{0395}":
            return "*E";
        case "\u{0396}":
            return "*Z";
        case "\u{0397}":
            return "*H";
        case "\u{0398}":
            return "*Q";
        case "\u{0399}":
            return "*I";
        case "\u{039A}":
            return "*K";
        case "\u{039B}":
            return "*L";
        case "\u{039C}":
            return "*M";
        case "\u{039D}":
            return "*N";
        case "\u{039E}":
            return "*C";
        case "\u{039F}":
            return "*O";
        case "\u{03A0}":
            return "*P";
        case "\u{03A1}":
            return "*R";
        case "\u{03A3}":
            return "*S";
        case "\u{03A4}":
            return "*T";
        case "\u{03A5}":
            return "*U";
        case "\u{03A6}":
            return "*F";
        case "\u{03A7}":
            return "*X";
        case "\u{03A8}":
            return "*Y";
        case "\u{03A9}":
            return "*W";
        case "\u{03B1}":
            return "A";
        case "\u{03B2}":
            return "B";
        case "\u{03B3}":
            return "G";
        case "\u{03B4}":
            return "D";
        case "\u{03B5}":
            return "E";
        case "\u{03B6}":
            return "Z";
        case "\u{03B7}":
            return "H";
        case "\u{03B8}":
            return "Q";
        case "\u{03B9}":
            return "I";
        case "\u{03BA}":
            return "K";
        case "\u{03BB}":
            return "L";
        case "\u{03BC}":
            return "M";
        case "\u{03BD}":
            return "N";
        case "\u{03BE}":
            return "C";
        case "\u{03BF}":
            return "O";
        case "\u{03C0}":
            return "P";
        case "\u{03C1}":
            return "R";
        case "\u{03C2}":
        case "\u{03C3}":
            return "S";
        case "\u{03C4}":
            return "T";
        case "\u{03C5}":
            return "U";
        case "\u{03C6}":
            return "F";
        case "\u{03C7}":
            return "X";
        case "\u{03C8}":
            return "Y";
        case "\u{03C9}":
            return "W";
        case "\u{03CA}":
            return "I+";
        case "\u{03CB}":
            return "U+";
        case "\u{1F00}":
            return "A)";
        case "\u{1F01}":
            return "A(";
        case "\u{1F02}":
        case "\u{1F00}\u{0300}":
        case "\u{03B1}\u{0313}\u{0300}":
            return "A)\\";
        case "\u{1F03}":
        case "\u{F101}\u{0300}":
        case "\u{03B1}\u{0314}\u{0300}":
            return "A(\\";
        case "\u{1F04}":
            return "A)/";
        case "\u{1F05}":
            return "A(/";
        case "\u{1F10}":
            return "E)";
        case "\u{1F11}":
            return "E(";
        case "\u{1F12}":
        case "\u{1F10}\u{0300}":
        case "\u{03B5}\u{0313}\u{0300}":
            return "E)\\";
        case "\u{1F13}":
        case "\u{1F11}\u{0300}":
        case "\u{03B5}\u{0314}\u{0300}":
            return "E(\\";
        case "\u{1F14}":
            return "E)/";
        case "\u{1F15}":
            return "E(/";
        case "\u{1F20}":
            return "H)";
        case "\u{1F21}":
            return "H(";
        case "\u{1F22}":
        case "\u{1F20}\u{0300}":
        case "\u{03B7}\u{0313}\u{0300}":
            return "H)\\";
        case "\u{1F23}":
        case "\u{1F21}\u{0300}":
        case "\u{03B7}\u{0314}\u{0300}":
            return "H(\\";
        case "\u{1F24}":
            return "H)/";
        case "\u{1F25}":
            return "H(/";
        case "\u{1F30}":
            return "I)";
        case "\u{1F31}":
            return "I(";
        case "\u{1F32}":
        case "\u{1F30}\u{0300}":
        case "\u{03B9}\u{0313}\u{0300}":
            return "I)\\";
        case "\u{1F33}":
        case "\u{1F31}\u{0300}":
        case "\u{03B9}\u{0314}\u{0300}":
            return "I(\\";
        case "\u{1F34}":
            return "I)/";
        case "\u{1F35}":
            return "I(/";
        case "\u{1F40}":
            return "O)";
        case "\u{1F41}":
            return "O(";
        case "\u{1F42}":
        case "\u{1F40}\u{0300}":
        case "\u{03BF}\u{0313}\u{0300}":
            return "O)\\";
        case "\u{1F43}":
        case "\u{1F41}\u{0300}":
        case "\u{03BF}\u{0314}\u{0300}":
            return "O(\\";
        case "\u{1F44}":
            return "O)/";
        case "\u{1F45}":
            return "O(/";
        case "\u{1F50}":
            return "U)";
        case "\u{1F51}":
            return "U(";
        case "\u{1F52}":
        case "\u{1F50}\u{0300}":
        case "\u{03C5}\u{0313}\u{0300}":
            return "U)\\";
        case "\u{1F53}":
        case "\u{1F51}\u{0300}":
        case "\u{03C5}\u{0314}\u{0300}":
            return "U(\\";
        case "\u{1F54}":
            return "U)/";
        case "\u{1F55}":
            return "U(/";
        case "\u{1F60}":
            return "W)";
        case "\u{1F61}":
            return "W(";
        case "\u{1F62}":
        case "\u{1F60}\u{0300}":
        case "\u{03C9}\u{0313}\u{0300}":
            return "W)\\";
        case "\u{1F63}":
        case "\u{1F61}\u{0300}":
        case "\u{03C9}\u{0314}\u{0300}":
            return "W(\\";
        case "\u{1F64}":
            return "W)/";
        case "\u{1F65}":
            return "W(/";
        case "\u{1F06}":
            return "A)=";
        case "\u{1F07}":
            return "A(=";
        case "\u{1F26}":
            return "H)=";
        case "\u{1F27}":
            return "H(=";
        case "\u{1F36}":
            return "I)=";
        case "\u{1F37}":
            return "I(=";
        case "\u{1F56}":
            return "U)=";
        case "\u{1F57}":
            return "U(=";
        case "\u{1F66}":
        case "\u{1F67}":
            return "W)=";
        case "\u{1F08}":
            return "*A)";
        case "\u{1F09}":
            return "*A(";
        case "\u{1F0A}":
        case "\u{1F08}\u{0300}":
        case "\u{0391}\u{0313}\u{0300}":
            return "*A)\\";
        case "\u{1F0B}":
        case "\u{1F09}\u{0300}":
        case "\u{0391}\u{0314}\u{0300}":
            return "*A(\\";
        case "\u{1F0C}":
            return "*A)/";
        case "\u{1F0F}":
            return "*A(/";
        case "\u{1F18}":
            return "*E)";
        case "\u{1F19}":
            return "*E(";
        case "\u{1F1A}":
        case "\u{1F18}\u{0300}":
        case "\u{0395}\u{0313}\u{0300}":
            return "*E)\\";
        case "\u{1F1B}":
        case "\u{1F19}\u{0300}":
        case "\u{0395}\u{0314}\u{0300}":
            return "*E(\\";
        case "\u{1F1C}":
            return "*E)/";
        case "\u{1F1D}":
            return "*E(/";
        case "\u{1F28}":
            return "*H)";
        case "\u{1F29}":
            return "*H(";
        case "\u{1F2A}":
        case "\u{1F28}\u{0300}":
        case "\u{0397}\u{0313}\u{0300}":
            return "*H)\\";
        case "\u{1F2B}":
        case "\u{1F29}\u{0300}":
        case "\u{0397}\u{0314}\u{0300}":
            return "*H(\\";
        case "\u{1F2C}":
            return "*H)/";
        case "\u{1F2E}":
            return "*H)=";
        case "\u{1F2F}":
            return "*H(/";
        case "\u{1F38}":
            return "*I)";
        case "\u{1F39}":
            return "*I(";
        case "\u{1F3C}":
            return "*I)/";
        case "\u{1F3F}":
            return "*I(=";
        case "\u{1F48}":
            return "*O)";
        case "\u{1F49}":
            return "*O(";
        case "\u{1F4A}":
        case "\u{1F48}\u{0300}":
        case "\u{039F}\u{0313}\u{0300}":
            return "*O)\\";
        case "\u{1F4B}":
        case "\u{1F49}\u{0300}":
        case "\u{039F}\u{0314}\u{0300}":
            return "*O(\\";
        case "\u{1F4C}":
            return "*O)/";
        case "\u{1F4D}":
            return "*O(/";
        case "\u{1F58}":
            return "*U)";
        case "\u{1F59}":
            return "*U(";
        case "\u{1F5A}":
        case "\u{1F58}\u{0300}":
        case "\u{03A5}\u{0313}\u{0300}":
            return "*U)\\";
        case "\u{1F5B}":
        case "\u{1F59}\u{0300}":
        case "\u{03A5}\u{0314}\u{0300}":
            return "*U(\\";
        case "\u{1F5D}":
            return "*U(/";
        case "\u{1F5F}":
            return "*U(=";
        case "\u{1F68}":
            return "*W)";
        case "\u{1F69}":
            return "*W(";
        case "\u{1F6C}":
            return "*W)/";
        case "\u{1F6F}":
            return "*W(/";
        case "\u{1F0E}":
            return "*A)=";
        case "\u{1F6E}":
            return "*W)=";
        case "\u{1F70}":
        case "\u{03B1}\u{0300}":
            return "A\\";
        case "\u{1F71}":
            return "A/";
        case "\u{1F72}":
        case "\u{03B5}\u{0300}":
            return "E\\";
        case "\u{1F73}":
            return "E/";
        case "\u{1F74}":
        case "\u{03B7}\u{0300}":
            return "H\\";
        case "\u{1F75}":
            return "H/";
        case "\u{1F76}":
        case "\u{03B9}\u{0300}":
            return "I\\";
        case "\u{1F77}":
            return "I/";
        case "\u{1F78}":
        case "\u{03BF}\u{0300}":
            return "O\\";
        case "\u{1F79}":
            return "O/";
        case "\u{1F7A}":
        case "\u{03C5}\u{0300}":
            return "U\\";
        case "\u{1F7B}":
            return "U/";
        case "\u{1F7C}":
        case "\u{03C9}\u{0300}":
            return "W\\";
        case "\u{1F7D}":
            return "W/";
        case "\u{1F84}":
            return "A)/|";
        case "\u{1F85}":
            return "A(/|";
        case "\u{1F90}":
            return "H)|";
        case "\u{1F91}":
            return "H(|";
        case "\u{1F94}":
            return "H)/|";
        case "\u{1F96}":
            return "H)=|";
        case "\u{1F97}":
            return "H(=|";
        case "\u{1FA0}":
            return "W)|";
        case "\u{1FA7}":
            return "W(=|";
        case "\u{1FB6}":
            return "A=";
        case "\u{1FC6}":
            return "H=";
        case "\u{1FD6}":
            return "I=";
        case "\u{1FE6}":
            return "U=";
        case "\u{1FF6}":
            return "W=";
        case "\u{1FD2}":
        case "\u{03CA}\u{0300}":
        case "\u{03B9}\u{0308}\u{0300}":
            return "I\\+";
        case "\u{1FD3}":
            return "I/+";
        case "\u{1FE2}":
        case "\u{03CB}\u{0300}":
        case "\u{03C5}\u{0308}\u{0300}":
            return "U\\+";
        case "\u{1FE3}":
            return "U/+";
        case "\u{1FB3}":
            return "A|";
        case "\u{1FB4}":
            return "A/|";
        case "\u{1FC3}":
            return "H|";
        case "\u{1FC4}":
            return "H/|";
        case "\u{1FF3}":
            return "W|";
        case "\u{1FF4}":
            return "W|/";
        case "\u{1FB7}":
            return "A=|";
        case "\u{1FC7}":
            return "H=|";
        case "\u{1FF7}":
            return "W=|";
        case "\u{1FE4}":
            return "R(";
        case "\u{1FEC}":
            return "*R(";
        case "\u{037E}":
            return "?";
        case "\u{0387}":
            return ":";
        default:
            return $unicodeChar;
    }
}