<?php

include "dbconnect.php";

$db = getDbConnection();

function importText($csvFile, $method, $version) {
    switch($method) {
        case 1: // private CSV generated by local Python interpreter
            return importPyStyle($csvFile);
            break;
        default:
            // needs interpretation
            $cmd = escapeshellcmd('hexapla/strong_interpreter.py ' . $version . ' ' . $csvFile);
            $output = shell_exec($cmd);
            return importText($output, 1, $version);
    }
}

/**
 * @param $csvFile
 * @return int
 */
function importPyStyle($csvFile) {
    global $db;
    $handle = fopen($csvFile);

    while (($data = fgetcsv($handle)) !== FALSE) {
        $text = $data[0];
        $version = $data[1];
        $division = $data[2];
        $chapter = $data[3];
        $verse = $data[4];
        $placement = $data[5];
        $strong = $data[6];
        $value = $data[7];

        if (strpos($strong,",") > 0) {
            $strongInit = substr($strong,0,1);
            $associatedStrongs = explode(",",$strong);
            $associatedStrongs[1] = $strongInit . $associatedStrongs[1];
            $strong = implode("|",$associatedStrongs);
        }

        $sql = "INSERT INTO `` VALUES($text, $version, $division, $chapter, $verse, $placement, $strong, $value)";
        pg_query($db, $sql);
    }

    fclose($handle);

    return 0; // no errors
}